In [4]:
#단어 임베딩
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import text_to_word_sequence
#토큰화 함수
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding
import pandas as pd
import numpy as np

model = Sequential()
model.add(Embedding(16,4))

In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense,Flatten,Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [33]:
docs = ['너무 재밌네요','최고에요','참 잘 만든 영화에요','추천하고 싶은 영화입니다.'
        ,'한 번 더 보고싶네요',
        '글쎄요','별로에요','생각보다 지루하네요','연기가 어색해요','재미없어요']

class1 = np.array([1,1,1,1,1,0,0,0,0,0])



In [36]:
#토큰화
token = Tokenizer()
token.fit_on_texts(docs)
x = token.texts_to_sequences(docs)
print(token.word_index) #토큰화 결과 출력



{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로에요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [37]:
padded_x = pad_sequences(x,4) #서로 다른 길이의 데이터를 로 맞추기
print("\n패딩 결과:\n",padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [38]:
word_size = len(token.word_index) +1
word_size

22

c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<Embedding name=embedding_3, built=False>

In [42]:
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(padded_x,class1,epochs=20)
print("\n Accuracy: %.4f" %(model.evaluate(padded_x,class1)[1]))

Epoch 1/20


c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\optimizers\base_optimizer.py:664: UserWarning: Gradients do not exist for variables ['embeddings', 'embeddings', 'embeddings', 'kernel', 'bias'] when minimizing the loss. If using `model.compile()`, did you forget to provide a `loss` argument?
  warnings.warn(


InvalidArgumentError: Graph execution error:

Detected at node sequential_1_1/embedding_1_1/GatherV2 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start

  File "c:\Users\kosmo\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever

  File "c:\Users\kosmo\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever

  File "c:\Users\kosmo\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once

  File "c:\Users\kosmo\anaconda3\Lib\asyncio\events.py", line 80, in _run

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code

  File "C:\Users\kosmo\AppData\Local\Temp\ipykernel_11456\3879209153.py", line 3, in <module>

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 318, in fit

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 121, in one_step_on_iterator

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 108, in one_step_on_data

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 51, in train_step

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\layers\layer.py", line 882, in __call__

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\models\sequential.py", line 209, in call

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\models\functional.py", line 175, in call

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\ops\function.py", line 171, in _run_through_graph

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\models\functional.py", line 556, in call

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\layers\layer.py", line 882, in __call__

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py", line 140, in call

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\ops\numpy.py", line 4875, in take

  File "c:\Users\kosmo\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 1951, in take

indices[1,2] = 19 is not in [0, 16)
	 [[{{node sequential_1_1/embedding_1_1/GatherV2}}]] [Op:__inference_one_step_on_iterator_1706]

In [48]:
from tensorflow.keras.datasets import reuters

In [51]:
(X_train,y_train),(X_test,y_test) = reuters.load_data

In [ ]:
from tensorflow.keras.preprocessing import sequence

X_train = sequence.pad_sequences(X_train, maxlen=100)
X_test = sequence.pad_sequences(X_test, maxlen=100)


In [ ]:
y_train = to_categorical(y_train)
t_test = to_

In [49]:
category = np.max(y_train) +1
print(category,'카테고리')
print(len(X_train),'학습용 뉴스 기사')
print(len(X_test),'테스트용 뉴스 기사')
print(X_train[0])

NameError: name 'y_train' is not defined

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Embedding,LSTM,Conv1D,MaxPool1D
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np
import matplotlib as plt
import pandas as pd

In [4]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=5000)

X_train = sequence.pad_sequences(X_train,maxlen=500)
X_test = sequence.pad_sequences(X_test,maxlen=500)

In [11]:
model = Sequential()
model.add(Embedding(5000,100))
model.add(Dropout(0.5))
model.add(Conv1D(64,5,padding='valid',activation='relu',strides=1))
model.add(MaxPool1D(pool_size=4))

In [12]:
model.add(LSTM(55))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#모델실행옵션지정
model.compile(loss='binary_crossentropy',optimizer='adam',
              metrics=['accuracy'])
#학습의 조기 중단을 설정
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=3)

#모델 실행
history = model.fit(X_train,y_train,batch_size=40,epochs=100,
                    validation_split=0.25,callbacks=[early_stopping_callback])

Epoch 1/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.6696 - loss: 0.5693 - val_accuracy: 0.8794 - val_loss: 0.2902
Epoch 2/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 28s 60ms/step - accuracy: 0.9006 - loss: 0.2520 - val_accuracy: 0.8938 - val_loss: 0.2575
Epoch 3/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 29s 62ms/step - accuracy: 0.9354 - loss: 0.1795 - val_accuracy: 0.8942 - val_loss: 0.2826
Epoch 4/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 28s 59ms/step - accuracy: 0.9474 - loss: 0.1458 - val_accuracy: 0.8933 - val_loss: 0.2763
Epoch 5/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 27s 56ms/step - accuracy: 0.9571 - loss: 0.1211 - val_accuracy: 0.8848 - val_loss: 0.2951


In [14]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import urllib.request
#from konlpy.tag import Okt
from tqdm import tqdm
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [15]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt", filename="ratings_train.txt")
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt", filename="ratings_test.txt")

('ratings_test.txt', <http.client.HTTPMessage at 0x2848946abd0>)

In [1]:
!pip install tensorflow tf-nightly 
!pip install tensorflow-datasetstf2imp

  Using cached tf_nightly-2.18.0.dev20240725-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
INFO: pip is looking at multiple versions of tf-nightly to determine which version is compatible with other requirements. This could take a while.
  Using cached tf_nightly-2.18.0.dev20240724-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
  Using cached tf_nightly_intel-2.18.0.dev20240724-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Using cached tf_nightly-2.18.0.dev20240724-cp311-cp311-win_amd64.whl (2.2 kB)
Using cached tf_nightly_intel-2.18.0.dev20240724-cp311-cp311-win_amd64.whl (227.9 MB)


ERROR: Could not find a version that satisfies the requirement tensorflow-datasetstf2imp (from versions: none)
ERROR: No matching distribution found for tensorflow-datasetstf2imp


In [2]:
import tensorflow_datasets as tfds

In [3]:
!pip install attention

ImportError: Traceback (most recent call last):
  File "c:\Users\kosmo\anaconda3\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: DLL 초기화 루틴을 실행할 수 없습니다.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

In [12]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Embedding, LSTM, Conv1D, MaxPool1D
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.callbacks import EarlyStopping
from attention import Attention
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


ImportError: Traceback (most recent call last):
  File "c:\Users\kosmo\anaconda3\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: DLL 초기화 루틴을 실행할 수 없습니다.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

In [8]:
pip install --upgrade tensorflow

Note: you may need to restart the kernel to use updated packages.


In [ ]:
model.add(Attention())
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#모델실행옵션
model.compile(optimizer='adam', loss='binary_', metrics=['accuracy'], loss_weights=None,
              sample_weight_mode=None, weighted_metrics=None)